name: 'SimpleCov resultset difference'
description: 'Creates a comment in the pull-request comparing two SimpleCov resultset files.'
author: Kazuki Nishikawa
inputs:
  base-resultset-path:
    description: 'SimpleCov generated "resultset.json" file path from the base branch'
    required: true
  head-resultset-path:
    description: 'SimpleCov generated "resultset.json" file path from the head branch'
    required: true
  token:
    description: 'Github generated token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
